# 服务端口
server:
  port: 8082
spring:
  # 应用名称
  application:
    name: yixiu-assist
  # 配置环境
  profiles:
    active: dev
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${mysql.username}
    password: ${mysql.password}
    # 连接池配置
    hikari:
      pool-name: ${mysql.hikari.pool-name}
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1
      connection-timeout: 30000
  # 邮箱配置
  mail:
    host: ${mail.host}
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: UTF-8
  # 文件上传配置
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 所有上传文件最大大小
      max-request-size: 50MB

# Redis配置
redisson:
  enabled: true
  address: ${redis.host}:${redis.port}
  password: ${redis.password}
# 多级缓存
multi:
  cache:
    l1-caches:
      - cache-name: userCache
        expire: 300 # 缓存过期时间
# RocketMQ配置
rocketmq:
  name-server: ${mq.host}:${mq.port}
  producer:
    group: ${mq.producer.group}
    send-message-timeout: 3000
    max-message-size: 4096
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 2
  consumer:
    group: ${mq.consumer.group}
    pull-batch-size: 10
# 微信配置
wx:
  app-id: ${wechat.app-id}
  token: ${wechat.token}
  original-id: ${wechat.original-id}
  app-secret: ${wechat.app-secret}
  template-id: ${wechat.template-id}
  template-url: ${wechat.template-url}
# sa-token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  token-prefix: Bearer
  jwt-secret-key: yixiu
# OSS配置
oss:
  enabled: true
  endpoint: ${oss.minio.endpoint}
  access-key: ${oss.minio.access-key}
  secret-key: ${oss.minio.secret-key}
  bucket-name: ${oss.minio.bucket-name}